# Generated by Django 2.0.5 on 2018-05-27 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinedebarrio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Films',
        ),
    ]
