# Generated by Django 2.0.5 on 2018-05-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinedebarrio', '0002_auto_20180527_1306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Films',
            new_name='Film',
        ),
    ]
